name: 'CircleCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Python 
      run: python3 -u -main.py

    - name: Output the outputs of the integration test of the action
      run: |
        echo "run"
